version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      golang-x:
        patterns: ["golang.org/x/*"]
      anchore:
        patterns: ["github.com/anchore/*"]
      k8s:
        patterns: ["k8s.io/*"]
      google-cloud:
        patterns: ["cloud.google.com/*", "google.golang.org/*"]

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
