apiVersion: 1
datasources:
  - name: Grumble
    uid: grumble-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://grumble-server:8080
    isDefault: true
    editable: false
