// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pkg/proto/grumble.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrumbleServer_Connect_FullMethodName = "/grumble.v1.GrumbleServer/Connect"
)

// GrumbleServerClient is the client API for GrumbleServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrumbleServer is the central aggregation service.
// Agents in each cluster connect outbound to this server.
type GrumbleServerClient interface {
	// Connect establishes a persistent bidirectional stream between
	// a cluster agent and the server. The agent initiates this connection,
	// allowing it to work behind firewalls and NAT.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerCommand], error)
}

type grumbleServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrumbleServerClient(cc grpc.ClientConnInterface) GrumbleServerClient {
	return &grumbleServerClient{cc}
}

func (c *grumbleServerClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrumbleServer_ServiceDesc.Streams[0], GrumbleServer_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrumbleServer_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerCommand]

// GrumbleServerServer is the server API for GrumbleServer service.
// All implementations must embed UnimplementedGrumbleServerServer
// for forward compatibility.
//
// GrumbleServer is the central aggregation service.
// Agents in each cluster connect outbound to this server.
type GrumbleServerServer interface {
	// Connect establishes a persistent bidirectional stream between
	// a cluster agent and the server. The agent initiates this connection,
	// allowing it to work behind firewalls and NAT.
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerCommand]) error
	mustEmbedUnimplementedGrumbleServerServer()
}

// UnimplementedGrumbleServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrumbleServerServer struct{}

func (UnimplementedGrumbleServerServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGrumbleServerServer) mustEmbedUnimplementedGrumbleServerServer() {}
func (UnimplementedGrumbleServerServer) testEmbeddedByValue()                       {}

// UnsafeGrumbleServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrumbleServerServer will
// result in compilation errors.
type UnsafeGrumbleServerServer interface {
	mustEmbedUnimplementedGrumbleServerServer()
}

func RegisterGrumbleServerServer(s grpc.ServiceRegistrar, srv GrumbleServerServer) {
	// If the following call panics, it indicates UnimplementedGrumbleServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrumbleServer_ServiceDesc, srv)
}

func _GrumbleServer_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrumbleServerServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrumbleServer_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerCommand]

// GrumbleServer_ServiceDesc is the grpc.ServiceDesc for GrumbleServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrumbleServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grumble.v1.GrumbleServer",
	HandlerType: (*GrumbleServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _GrumbleServer_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/grumble.proto",
}
