// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/proto/grumble.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage is sent from agent → server
type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // unique agent identifier
	ClusterId string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // cluster name/identifier
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Inventory
	//	*AgentMessage_ScanResult
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetInventory() *PodInventory {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *AgentMessage) GetScanResult() *ScanResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ScanResult); ok {
			return x.ScanResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Registration `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type AgentMessage_Inventory struct {
	Inventory *PodInventory `protobuf:"bytes,4,opt,name=inventory,proto3,oneof"`
}

type AgentMessage_ScanResult struct {
	ScanResult *ScanResult `protobuf:"bytes,5,opt,name=scan_result,json=scanResult,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Inventory) isAgentMessage_Payload() {}

func (*AgentMessage_ScanResult) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

// ServerCommand is sent from server → agent
type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ServerCommand_Scan
	//	*ServerCommand_Config
	//	*ServerCommand_Ping
	Command       isServerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetCommand() isServerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServerCommand) GetScan() *ScanRequest {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *ServerCommand) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ServerCommand) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerCommand_Command interface {
	isServerCommand_Command()
}

type ServerCommand_Scan struct {
	Scan *ScanRequest `protobuf:"bytes,1,opt,name=scan,proto3,oneof"`
}

type ServerCommand_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type ServerCommand_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ServerCommand_Scan) isServerCommand_Command() {}

func (*ServerCommand_Config) isServerCommand_Command() {}

func (*ServerCommand_Ping) isServerCommand_Command() {}

// Registration is sent once on connect
type Registration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	K8SVersion     string                 `protobuf:"bytes,2,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	AgentVersion   string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	GrypeDbVersion string                 `protobuf:"bytes,4,opt,name=grype_db_version,json=grypeDbVersion,proto3" json:"grype_db_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Registration) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *Registration) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Registration) GetGrypeDbVersion() string {
	if x != nil {
		return x.GrypeDbVersion
	}
	return ""
}

// PodInventory is sent when pod state changes in the cluster
type PodInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*PodInfo             `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInventory) Reset() {
	*x = PodInventory{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInventory) ProtoMessage() {}

func (x *PodInventory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInventory.ProtoReflect.Descriptor instead.
func (*PodInventory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{3}
}

func (x *PodInventory) GetPods() []*PodInfo {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *PodInventory) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Phase         string                 `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{4}
}

func (x *PodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodInfo) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *PodInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PodInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

// ScanResult contains Grype findings for a single image,
// including the full package list (SBOM) for dependency queries.
type ScanResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScanId         string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest    string                 `protobuf:"bytes,3,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	ClusterId      string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Vulns          []*Vulnerability       `protobuf:"bytes,5,rep,name=vulns,proto3" json:"vulns,omitempty"`
	ScannedAt      int64                  `protobuf:"varint,6,opt,name=scanned_at,json=scannedAt,proto3" json:"scanned_at,omitempty"`
	GrypeDbVersion string                 `protobuf:"bytes,7,opt,name=grype_db_version,json=grypeDbVersion,proto3" json:"grype_db_version,omitempty"`
	Packages       []*Package             `protobuf:"bytes,8,rep,name=packages,proto3" json:"packages,omitempty"` // full package/dependency list
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{5}
}

func (x *ScanResult) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResult) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ScanResult) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ScanResult) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ScanResult) GetVulns() []*Vulnerability {
	if x != nil {
		return x.Vulns
	}
	return nil
}

func (x *ScanResult) GetScannedAt() int64 {
	if x != nil {
		return x.ScannedAt
	}
	return 0
}

func (x *ScanResult) GetGrypeDbVersion() string {
	if x != nil {
		return x.GrypeDbVersion
	}
	return ""
}

func (x *ScanResult) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

// Package represents a single dependency found in an image (SBOM entry)
type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`         // e.g. "java", "python", "npm", "apk", "deb", "rpm"
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"` // e.g. "java", "python", "javascript"
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"` // path inside the image where it was found
	Purl          string                 `protobuf:"bytes,6,opt,name=purl,proto3" json:"purl,omitempty"`         // package URL (pkg:type/name@version)
	License       string                 `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`   // SPDX license expression
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{6}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Package) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Package) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Package) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *Package) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

type Vulnerability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // CVE-YYYY-NNNNN
	PackageName   string                 `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	FixedIn       string                 `protobuf:"bytes,4,opt,name=fixed_in,json=fixedIn,proto3" json:"fixed_in,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // CRITICAL, HIGH, MEDIUM, LOW, NEGLIGIBLE
	CvssScore     string                 `protobuf:"bytes,6,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{7}
}

func (x *Vulnerability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vulnerability) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Vulnerability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Vulnerability) GetFixedIn() string {
	if x != nil {
		return x.FixedIn
	}
	return ""
}

func (x *Vulnerability) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Vulnerability) GetCvssScore() string {
	if x != nil {
		return x.CvssScore
	}
	return ""
}

func (x *Vulnerability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ScanRequest tells the agent to scan a specific image
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{8}
}

func (x *ScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// ConfigUpdate pushes new config to the agent
type ConfigUpdate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ScanIntervalSeconds int32                  `protobuf:"varint,1,opt,name=scan_interval_seconds,json=scanIntervalSeconds,proto3" json:"scan_interval_seconds,omitempty"`
	MaxConcurrentScans  int32                  `protobuf:"varint,2,opt,name=max_concurrent_scans,json=maxConcurrentScans,proto3" json:"max_concurrent_scans,omitempty"`
	IgnoreNamespaces    []string               `protobuf:"bytes,3,rep,name=ignore_namespaces,json=ignoreNamespaces,proto3" json:"ignore_namespaces,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigUpdate) GetScanIntervalSeconds() int32 {
	if x != nil {
		return x.ScanIntervalSeconds
	}
	return 0
}

func (x *ConfigUpdate) GetMaxConcurrentScans() int32 {
	if x != nil {
		return x.MaxConcurrentScans
	}
	return 0
}

func (x *ConfigUpdate) GetIgnoreNamespaces() []string {
	if x != nil {
		return x.IgnoreNamespaces
	}
	return nil
}

// Heartbeat / Ping for connection health
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pkg_proto_grumble_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grumble_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grumble_proto_rawDescGZIP(), []int{11}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_proto_grumble_proto protoreflect.FileDescriptor

const file_pkg_proto_grumble_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/grumble.proto\x12\n" +
	"grumble.v1\"\xb7\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x126\n" +
	"\bregister\x18\x03 \x01(\v2\x18.grumble.v1.RegistrationH\x00R\bregister\x128\n" +
	"\tinventory\x18\x04 \x01(\v2\x18.grumble.v1.PodInventoryH\x00R\tinventory\x129\n" +
	"\vscan_result\x18\x05 \x01(\v2\x16.grumble.v1.ScanResultH\x00R\n" +
	"scanResult\x125\n" +
	"\theartbeat\x18\x06 \x01(\v2\x15.grumble.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xa5\x01\n" +
	"\rServerCommand\x12-\n" +
	"\x04scan\x18\x01 \x01(\v2\x17.grumble.v1.ScanRequestH\x00R\x04scan\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x18.grumble.v1.ConfigUpdateH\x00R\x06config\x12&\n" +
	"\x04ping\x18\x03 \x01(\v2\x10.grumble.v1.PingH\x00R\x04pingB\t\n" +
	"\acommand\"\x9d\x01\n" +
	"\fRegistration\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vk8s_version\x18\x02 \x01(\tR\n" +
	"k8sVersion\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12(\n" +
	"\x10grype_db_version\x18\x04 \x01(\tR\x0egrypeDbVersion\"U\n" +
	"\fPodInventory\x12'\n" +
	"\x04pods\x18\x01 \x03(\v2\x13.grumble.v1.PodInfoR\x04pods\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x9e\x01\n" +
	"\aPodInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\"\xa8\x02\n" +
	"\n" +
	"ScanResult\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x03 \x01(\tR\vimageDigest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12/\n" +
	"\x05vulns\x18\x05 \x03(\v2\x19.grumble.v1.VulnerabilityR\x05vulns\x12\x1d\n" +
	"\n" +
	"scanned_at\x18\x06 \x01(\x03R\tscannedAt\x12(\n" +
	"\x10grype_db_version\x18\a \x01(\tR\x0egrypeDbVersion\x12/\n" +
	"\bpackages\x18\b \x03(\v2\x13.grumble.v1.PackageR\bpackages\"\xb1\x01\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x12\n" +
	"\x04purl\x18\x06 \x01(\tR\x04purl\x12\x18\n" +
	"\alicense\x18\a \x01(\tR\alicense\"\xd4\x01\n" +
	"\rVulnerability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bfixed_in\x18\x04 \x01(\tR\afixedIn\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\x06 \x01(\tR\tcvssScore\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"<\n" +
	"\vScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\xa1\x01\n" +
	"\fConfigUpdate\x122\n" +
	"\x15scan_interval_seconds\x18\x01 \x01(\x05R\x13scanIntervalSeconds\x120\n" +
	"\x14max_concurrent_scans\x18\x02 \x01(\x05R\x12maxConcurrentScans\x12+\n" +
	"\x11ignore_namespaces\x18\x03 \x03(\tR\x10ignoreNamespaces\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2S\n" +
	"\rGrumbleServer\x12B\n" +
	"\aConnect\x12\x18.grumble.v1.AgentMessage\x1a\x19.grumble.v1.ServerCommand(\x010\x01B)Z'github.com/mental-lab/grumble/pkg/protob\x06proto3"

var (
	file_pkg_proto_grumble_proto_rawDescOnce sync.Once
	file_pkg_proto_grumble_proto_rawDescData []byte
)

func file_pkg_proto_grumble_proto_rawDescGZIP() []byte {
	file_pkg_proto_grumble_proto_rawDescOnce.Do(func() {
		file_pkg_proto_grumble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_grumble_proto_rawDesc), len(file_pkg_proto_grumble_proto_rawDesc)))
	})
	return file_pkg_proto_grumble_proto_rawDescData
}

var file_pkg_proto_grumble_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_grumble_proto_goTypes = []any{
	(*AgentMessage)(nil),  // 0: grumble.v1.AgentMessage
	(*ServerCommand)(nil), // 1: grumble.v1.ServerCommand
	(*Registration)(nil),  // 2: grumble.v1.Registration
	(*PodInventory)(nil),  // 3: grumble.v1.PodInventory
	(*PodInfo)(nil),       // 4: grumble.v1.PodInfo
	(*ScanResult)(nil),    // 5: grumble.v1.ScanResult
	(*Package)(nil),       // 6: grumble.v1.Package
	(*Vulnerability)(nil), // 7: grumble.v1.Vulnerability
	(*ScanRequest)(nil),   // 8: grumble.v1.ScanRequest
	(*ConfigUpdate)(nil),  // 9: grumble.v1.ConfigUpdate
	(*Heartbeat)(nil),     // 10: grumble.v1.Heartbeat
	(*Ping)(nil),          // 11: grumble.v1.Ping
}
var file_pkg_proto_grumble_proto_depIdxs = []int32{
	2,  // 0: grumble.v1.AgentMessage.register:type_name -> grumble.v1.Registration
	3,  // 1: grumble.v1.AgentMessage.inventory:type_name -> grumble.v1.PodInventory
	5,  // 2: grumble.v1.AgentMessage.scan_result:type_name -> grumble.v1.ScanResult
	10, // 3: grumble.v1.AgentMessage.heartbeat:type_name -> grumble.v1.Heartbeat
	8,  // 4: grumble.v1.ServerCommand.scan:type_name -> grumble.v1.ScanRequest
	9,  // 5: grumble.v1.ServerCommand.config:type_name -> grumble.v1.ConfigUpdate
	11, // 6: grumble.v1.ServerCommand.ping:type_name -> grumble.v1.Ping
	4,  // 7: grumble.v1.PodInventory.pods:type_name -> grumble.v1.PodInfo
	7,  // 8: grumble.v1.ScanResult.vulns:type_name -> grumble.v1.Vulnerability
	6,  // 9: grumble.v1.ScanResult.packages:type_name -> grumble.v1.Package
	0,  // 10: grumble.v1.GrumbleServer.Connect:input_type -> grumble.v1.AgentMessage
	1,  // 11: grumble.v1.GrumbleServer.Connect:output_type -> grumble.v1.ServerCommand
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_proto_grumble_proto_init() }
func file_pkg_proto_grumble_proto_init() {
	if File_pkg_proto_grumble_proto != nil {
		return
	}
	file_pkg_proto_grumble_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Inventory)(nil),
		(*AgentMessage_ScanResult)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_pkg_proto_grumble_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerCommand_Scan)(nil),
		(*ServerCommand_Config)(nil),
		(*ServerCommand_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_grumble_proto_rawDesc), len(file_pkg_proto_grumble_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_grumble_proto_goTypes,
		DependencyIndexes: file_pkg_proto_grumble_proto_depIdxs,
		MessageInfos:      file_pkg_proto_grumble_proto_msgTypes,
	}.Build()
	File_pkg_proto_grumble_proto = out.File
	file_pkg_proto_grumble_proto_goTypes = nil
	file_pkg_proto_grumble_proto_depIdxs = nil
}
